### PR TITLE
Check for existence of speed list in fans

### LINKED ISSUE #283: Crash when reading fan speed
Not familiar with the API, but should this data.attributes be guarded by a null check? The fields above do it:

https://github.com/home-assistant/homebridge-homeassistant/blob/1a1759b8e47ece5550be627118dd43c3d00a9b7f/accessories/fan.js#L36

From the logs:

[2018-2-10 15:36:59] [HomeAssistant] fetching power state for: Office light
[2018-2-10 15:36:59] [HomeAssistant] fetching brightness for: Office light
[2018-2-10 15:36:59] [HomeAssistant] fetching brightness for: Downstairs hallway light
[2018-2-10 15:36:59] [HomeAssistant] fetching power state for: Downstairs hallway light
[2018-2-10 15:36:59] [HomeAssistant] fetching power state for: Kitchen light
[2018-2-10 15:36:59] [HomeAssistant] fetching brightness for: Kitchen light
[2018-2-10 15:36:59] [HomeAssistant] fetching power state for: Master bedroom fan light
[2018-2-10 15:36:59] [HomeAssistant] fetching brightness for: Master bedroom fan light
/homebridge/node_modules/homebridge-homeassistant/accessories/fan.js:99
          var speedList = data.attributes.speed_list;
                                          ^

TypeError: Cannot read property 'speed_list' of undefined
    at client.fetchState (/homebridge/node_modules/homebridge-homeassistant/accessories/fan.js:99:43)
    at request (/homebridge/node_modules/homebridge-homeassistant/index.js:109:9)
    at Request.request [as _callback] (/homebridge/node_modules/homebridge-homeassistant/index.js:101:7)
    at Request.self.callback (/homebridge/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/homebridge/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/homebridge/node_modules/request/request.js:1085:12)

### PR DESCRIPTION
**Pull request by schmittx**
- Fixes #283 
- Replaces PR #284 (this adds more robust checking in all calls)

### CODE REVIEW

File: accessories/fan.js [hunk 1]
```diff
@@ -30,15 +30,14 @@ function HomeAssistantFan(log, data, client) {
   } else {
     this.serial = data.entity_id;
   }
-  this.client = client;
-  this.log = log;
-
-  var speedList = data.attributes.speed_list;
-  if (speedList) {
+  if (data.attributes.speed_list) {
```
Comment (kodek) [inline accessories/fan.js]: I apologize for my lack of experience with JS, but is it not necessary to check that `data.attributes` is also defined?

Comment (kodek) [reply accessories/fan.js]: I see from my stack trace in #283 that the culprit is actually `speed_list`, so I'm going to assume that the `attributes` check isn't necessary. If that's the case, I'm not sure why the fields above are checking for `attributes`. Would you mind clarifying how this works? Thanks!

Comment (schmittx) [reply accessories/fan.js]: Your original trace in #283 showed that `speed_list` didn't exist when it called `getRotationSpeed`  at line 99.

Checking for 'data.attributes.speed_list' accomplishes the same as checking for 'data', then checking for 'attributes', then checking for 'speed_list'; just less code.
